package com.Spryng.SpryngJavaSDK;

public enum SpryngResponse
{
    OK,
    MISSING_PARAMETER,
    USERNAME_TOO_LONG,
    USERNAME_TOO_SHORT,
    PASSWORD_TOO_LONG,
    PASSWORD_TOO_SHORT,
    DESTINATION_TOO_LONG,
    DESTINATION_TOO_SHORT,
    SENDER_TOO_LONG,
    SENDER_TOO_SHORT,
    CONTENT_TOO_LONG,
    CONTENT_TOO_SHORT,
    SECURITY_ERROR,
    UNKNOWN_ROUTE,
    ROUTE_ACCESS_VIOLATION,
    INSUFFICIENT_CREDITS,
    TECHNICAL_ERROR,
    SDK_ERROR
}
